### ISSUE TITLE
Comparison with apollo-link-error docs

### ISSUE THREAD

**Issue by dandv** [baleeds/apollo-link-refresh-token#3]
In what ways, if any, would this package be obsoleted when this PR gets accepted? https://github.com/apollographql/apollo-link/pull/825/files

**Comment by baleeds** [comment]
I'm glad to see the docs being updated! This library has never done anything too large. I'll probably keep using it for my own purposes because I like the way it reads, but I won't be surprised if others choose not to.

What do you think?
