### ISSUE TITLE
TS2305: Module apollo-link-refresh-token/dist"' has no exported member 'getTokenRefreshLink'.

### ISSUE THREAD

**Issue by raarts** [baleeds/apollo-link-refresh-token#5]
I don't understand because your module *does* provide types.
Am I doing something wrong?

Code taken from the example in the README.md

**Comment by baleeds** [comment]
Could you provide more information about your usage?  Is this a `create-react-app` project?

**Comment by raarts** [comment]
Sure, it's an expo project, where I just today started using Apollo 3.0 beta (because I guess it'll be out before I'm done). 

Here's my initial (working) code:
```ts

import { ApolloClient, InMemoryCache, ApolloProvider, createHttpLink, from, ApolloLink } from '@apollo/client';
import { setContext } from '@apollo/link-context';
import store from './store';

const httpLink = createHttpLink({
  uri: 'https://api.staging.my.net/v1/graphql',
});

const authLink = setContext((_, { headers }) => {
  const state = store.getState();
  const token = state.auth.access_token;
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
      // 'x-hasura-role': 'admin',
    },
  };
});

const client = new ApolloClient({
  link: from([(authLink as unknown) as ApolloLink, httpLink]),
  cache: new InMemoryCache(),
});
```

Next I went to lunch and when I returned, the next request bumped into an expired access token. Of course that needed to be handled, so initially I turned to apollo, couldn't not find anything relevant, and after googling around I decided to try your package, yarn'ed it, and pasted the import statement after the `setContext` import. And immediately eslint underlined it.

I gotta tell you I only started using typescript a few weeks ago, so I'm still always doubting myself on TS errors.

Related: how do people generally handle expired access tokens? It should be a widespread issue.

**Comment by raarts** [comment]
I solved this by completely moving to websockets, even for standard queries. Why? Because the `SubscriptionClient` takes an object with a `connectionParams` property which can be an async function. Yay!

Still a lot of work to implement it all, but it works. Thanks.
